environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install . -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest"

notifications:
  - provider: Email
    to:
      - yanqd0@outlook.com
    on_build_status_changed: true
